UPDATE "Order"
SET "status" = CASE
    WHEN "status" IN ('PENDING_SALES_REVIEW', 'SALES_REVIEWING', 'ON_HOLD') THEN 'REQUESTED'
    WHEN "status" IN ('SUPPLIER_ORDER_REQUIRED', 'SUPPLIER_ORDER_COMPLETED', 'DISPATCH_WAITING', 'DISPATCHING', 'DISPATCH_FAILED', 'DISPATCH_RETRY_SCHEDULED') THEN 'APPROVED'
    WHEN "status" IN ('READY_TO_SHIP', 'SHIPPING', 'DELIVERY_CONFIRM_PENDING', 'DELIVERY_CONFIRMED', 'DELIVERY_DISPUTED', 'ERP_INPUT_WAITING', 'ERP_INPUT_COMPLETED', 'INVOICE_WAITING', 'INVOICE_COMPLETED', 'COMPLETED') THEN 'SHIPPED'
    WHEN "status" = 'CANCELLED' THEN 'REJECTED'
    ELSE "status"
END
WHERE "status" NOT IN ('REQUESTED', 'CREDIT_OVER_LIMIT', 'REJECTED', 'APPROVED', 'DISPATCH_COMPLETED', 'SHIPPED');
